---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: changedetection
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: docker.io/dgtlmoon/changedetection.io
      tag: "0.40.0.4"
    env:
      TZ: Europe/Berlin
    service:
      main:
        ports:
          http:
            port: 5000
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external.home.arpa/enabled: "true"
          auth.home.arpa/enabled: "true"
        hosts:
          - host: "changedetection.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        enabled: true
        type: pvc
        mountPath: /datastore
        existingClaim: changedetection-data
