apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
stringData:
    config.json: ENC[AES256_GCM,data:jjwv+ROKJQFyZAjKrYoFpYTcDRZ4oIyP/v6zoxwg0RWycxEOuWmMhN66qgsTZKeR0A8nFdGGztgTw831c/05boj86RvDyx/aORLcis7Jsi4hzqr6nqGVcxll4y6eWQnoboT3oNFe4xQ+pHqMcQpH2NTjPm8TZzx0z0y1RjjHRkErEbueXb694V9zLMCMbAz8aG6xgOH9O1/4h3+wFM6PJA//xFsa98fa++fBNwvQDikBOnuBySulZ4W2P4C6Puf1GKwPICI/5VBb5QaRCuFQGBtkgj1pTq1zVEqm/JNRzabblzaJombv7x5YH4oUbfcqprFfYQ2lZ4sVAvKWEHvZGZ+2PjzFlqyES7POq+xJxV1g2Yk0FHuQkoA=,iv:mPG0c/dsZgfWdA4fZfFLz5ScS+tu/YY67se1a7NbjuM=,tag:bq+uwerm5xvESsKPlruTfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14pz5aw6h2m05jezv8yasyvalm0sqzpgwxkd8pusve2xwdwm22auqd3qu54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSG56ckk4QjdEZnBRZWxG
            VGlvN1pmQTQ5L1R1T0ZCYjZueEdBNjFoY1ZnCkc1aHIvbXFpSmUzV01zMGEyZURT
            a1JQR2JFVy9BYXRxN2ZHVXZKTFZxZ1UKLS0tIG9TLzltOHJVL293cmZLR2dkWDhz
            akF6UGtpQ0FNWkwzVEhDVmZMTGR0dm8KEpgH43qcDCp/o06JiNOB/6QG5rzYpzJ1
            SW4FdiNAU5dgj0qvJcLzpStTyZ4fh3r3h2cm4vZZ/YeMB3W9VaaySg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T21:32:26Z"
    mac: ENC[AES256_GCM,data:47pFWH/iu3uU3KB6Zx0Jqxv7gcYqHbG1Wczmu7Hd6/ibbEg3g2FED+p1rkrRsxENd1sjqihbYksqHHUOMI2rUEZoV+r2CxVzkxktETW8LrclYdFPmf+a6Mvy5wLfVhFbLIfcjH/Qqs6KkuU5E5w2FzjFY/MF1sZRAQFhRMOPoBs=,iv:2MFr5TLHXx8/YULxtPOfOa1dJenHuUMXTSxNqEfCxb8=,tag:IgTmtX88onAafgB+7NpLaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
