---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 6.48.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicas: 1
    # admin:
    #   existingSecret: grafana-secrets
    #   userKey: ADMIN_USER
    #   passwordKey: ADMIN_PASS
    grafana.ini:
      server:
        root_url: "https://grafana.${SECRET_DOMAIN}"
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: false
      log:
        mode: console
        filters: rendering:debug
      grafana_net:
        url: https://grafana.net
      auth.proxy:
        enabled: true
        header_name: Remote-User
        header_property: username
        headers: "Name:Remote-Name Email:Remote-Email"
      users:
        allow_sign_up: false
        auto_assign_org: true
        auto_assign_org_role: Admin
      date_formats:
        use_browser_locale: true
        default_timezone: browser
      panels:
        disable_sanitize_html: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    datasources:
      datasources.yaml:
        apiVersion: 1
        deleteDatasources:
          - name: Loki
            orgId: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://thanos-query:9090/
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            url: http://loki-read.monitoring.svc:3100
    dashboards:
      default:
        minio:
          gnetId: 13502
          revision: 10
          datasource: Prometheus
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
        # folderAnnotation: grafana_folder
        # provider:
        #   foldersFromFilesStructure: true
      datasources:
        enabled: true
        searchNamespace: ALL
    plugins:
      - grafana-piechart-panel
    #   - natel-discrete-panel
    #   - pr0ps-trackmap-panel
    #   - vonage-status-panel
    #   - grafana-worldmap-panel
    #   - grafana-clock-panel
    serviceMonitor:
      enabled: true
    persistence:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        auth.home.arpa/enabled: "true"
        external.home.arpa/enabled: "true"
      hosts:
        - "grafana.${SECRET_DOMAIN}"
