---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-mirror
  namespace: default
spec:
  schedule: "21 5,17 * * *"
  suspend: false
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 43200
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: rclone
              image: rclone/rclone:1.64.0
              envFrom:
                - secretRef:
                    name: s3-mirror-secret
              command:
                - /bin/sh
                - -c
                - >-
                  wget -qO- -t 5 -T 10 https://hc-ping.com/$(HC_UUID)/start ;
                  rclone sync --log-level ERROR --progress --config /config/rclone.conf minio:longhorn backblaze-crypt-longhorn: &&
                  wget -qO- -t 5 -T 10 https://hc-ping.com/$(HC_UUID)
              # rclone sync --log-level ERROR --progress --config /config/rclone.conf minio:$(MINIO_CNPG_BUCKET) backblaze-crypt:$(B2_CNPG_BUCKET) &&
              # rclone sync --log-level ERROR --progress --config /config/rclone.conf minio:$(MINIO_KOPIA_BUCKET) backblaze:$(B2_KOPIA_BUCKET) &&
              volumeMounts:
                - name: conf
                  mountPath: /config
                  readOnly: true
          volumes:
            - name: conf
              secret:
                secretName: s3-mirror-secret
                items:
                  - key: rclone.conf
                    path: rclone.conf
