---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-mirror
  namespace: default
spec:
  schedule: "21 5,17 * * *"
  suspend: false
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 43200
      template:
        metadata:
          annotations:
            kustomize.toolkit.fluxcd.io/substitute: disabled
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cnpg
              image: bitnami/minio-client:2023.8.8
              envFrom:
                - secretRef:
                    name: s3-mirror-secret
              command: ["/bin/bash", "-c"]
              # args: [ "while true; do sleep 30; done;" ]
              args:
                - |
                  mc alias set minio http://$(MINIO_HOST)/ $(MINIO_CNPG_USER) $(MINIO_CNPG_PASS)
                  mc alias set backblaze $(B2_ENDPOINT) $(B2_CNPG_USER) $(B2_CNPG_PASS)
                  mc mirror --fake minio/$(MINIO_CNPG_BUCKET) backblaze/$(B2_CNPG_BUCKET)

