---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-mirror
  namespace: default
spec:
  schedule: "21 5,17 * * *"
  suspend: false
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 43200
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: rclone
              image: rclone/rclone:1.63.1
              env:
                - name: MINIO_CNPG_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: s3-mirror-secret
                      key: MINIO_CNPG_BUCKET
                - name: B2_CNPG_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: s3-mirror-secret
                      key: B2_CNPG_BUCKET
                - name: MINIO_LONGHORN_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: s3-mirror-secret
                      key: MINIO_LONGHORN_BUCKET
                - name: B2_LONGHORN_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: s3-mirror-secret
                      key: B2_LONGHORN_BUCKET
              command: [ "/bin/bash", "-c", "--" ]
              args: [ "while true; do sleep 30; done;" ]
              # args:
              #   - |
              #     rclone sync --dry-run --config /config/rclone.conf minio:$(MINIO_CNPG_BUCKET) backblaze-crypt:$(B2_CNPG_BUCKET)
              volumeMounts:
                - name: conf
                  mountPath: /config
                  readOnly: true
          volumes:
            - name: conf
              secret:
                secretName: s3-mirror-secret
                items:
                  - key: rclone.conf
                    path: rclone.conf

