---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-mirror-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      engineVersion: v2
      data:
        MINIO_CNPG_BUCKET: "{{ .MINIO_CNPG_BUCKET }}"
        MINIO_CNPG_USER: "{{ .MINIO_CNPG_USER }}"
        MINIO_CNPG_PASS: "{{ .MINIO_CNPG_PASS }}"
        MINIO_LONGHORN_BUCKET: "{{ .MINIO_LONGHORN_BUCKET }}"
        MINIO_LONGHORN_USER: "{{ .MINIO_LONGHORN_USER }}"
        MINIO_LONGHORN_PASS: "{{ .MINIO_LONGHORN_PASS }}"
        B2_CNPG_BUCKET: "{{ .B2_CNPG_BUCKET }}"
        B2_CNPG_USER: "{{ .B2_CNPG_USER }}"
        B2_CNPG_PASS: "{{ .B2_CNPG_PASS }}"
        B2_LONGHORN_BUCKET: "{{ .B2_LONGHORN_BUCKET }}"
        B2_LONGHORN_USER: "{{ .B2_LONGHORN_USER }}"
        B2_LONGHORN_PASS: "{{ .B2_LONGHORN_PASS }}"
  dataFrom:
    - extract:
        key: MINIO
    - extract:
        key: BACKBLAZE
