---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
  annotations:
    kyverno.io/ignore: "true"
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15.5-8
  primaryUpdateStrategy: unsupervised
  storage:
    size: 60Gi
    storageClass: local-path
  superuserSecret:
    name: cloudnative-pg
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  resources:
    requests:
      memory: 600Mi
      cpu: 200m
    limits:
      memory: 4Gi
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 14d
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 2
      destinationPath: "s3://cloudnativepg/"
      endpointURL: "http://${NAS_ADDR_MINIO}"
      serverName: postgres-v3
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cloudnative-pg-s3
          key: ACCESS_SECRET_KEY
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
              - key: custom/has-nvme
                operator: In
                values: ["true"]
