---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres
  namespace: database
spec:
  schedule: "0 13 1 * * *"
  backupOwnerReference: self
  cluster:
    name: postgres
