---
- name: Clone Klipper repo
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/klipper3d/klipper.git
    dest: "{{ setup_klipper_dir }}"
    version: master

- name: Setup Klipper virtualenv
  become_user: "{{ ansible_user }}"
  ansible.builtin.pip:
    requirements: "{{ setup_klipper_dir }}/scripts/klippy-requirements.txt"
    virtualenv: "{{ setup_klipper_venv_dir }}"

- name: Create Klipper service
  ansible.builtin.template:
    src: klipper.service.j2
    dest: /etc/systemd/system/klipper.service
    mode: '0644'
    owner: root
    group: root

- name: Enable klipper service
  ansible.builtin.systemd:
    name: klipper.service
    daemon_reload: true
    enabled: true
