---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data-v1
  namespace: default
  labels:
    app.kubernetes.io/name: &name influxdb
    app.kubernetes.io/instance: *name
    # snapshot.home.arpa/enabled: "true"
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
