---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  dependsOn:
    - name: mosquitto
      namespace: home
  values:
    image:
      repository: koenkk/zigbee2mqtt
      tag: 1.27.0
      pullPolicy: IfNotPresent
    nameOverride: zigbee2mqtt
    env:
      TZ: Europe/Berlin
      ZIGBEE2MQTT_DATA: /data
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "networking-local-only@kubernetescrd"
        hosts:
          - host: "z2m.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    securityContext:
      privileged: true
    nodeSelector:
      feature.node.kubernetes.io/custom-sonoff-zigbee: "true"
    persistence:
      data:
        enabled: true
        type: pvc
        mountPath: /data
        existingClaim: zigbee2mqtt-data-v1
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_fe3bbcfff93aec11b2c29c957a0af07f-if00-port0
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.5.1
        env:
          TZ: "Europe/Berlin"
        workingDir: "/data"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/data/.vscode"
          - --extensions-dir
          - "/data/.vscode"
        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: "networking-authelia@kubernetescrd,networking-local-only@kubernetescrd"
          hosts:
            - host: "z2m-config.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
        volumeMounts:
          - name: data
            mountPath: /data
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 700Mi
