---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data-v1
  namespace: home
  labels:
    app.kubernetes.io/name: &name zigbee2mqtt
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
