---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # TODO: make it stateless - Redis, Postgres, LDAP
    image:
      repository: ghcr.io/authelia/authelia
      tag: 4.37.5
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    command: ["authelia"]
    args: ["--config", "/config/configuration.yaml"]
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 9091
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: "auth.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "auth.${SECRET_DOMAIN}"
    probes:
      liveness: &probe
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /api/health
            port: 9091
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probe
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        type: secret
        name: authelia-config-secret
        subPath: configuration.yaml
        mountPath: /config/configuration.yaml
        readOnly: true
      users:
        enabled: true
        type: secret
        name: authelia-users-secret
        subPath: users.yaml
        mountPath: /config/users.yaml
        readOnly: true
      data:
        enabled: true
        type: pvc
        mountPath: /config/storage
        existingClaim: authelia-data
