---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pulumi-secret
  namespace: infra
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      engineVersion: v2
      data:
        token: "{{ .PULUMI_ACCESS_TOKEN }}"
  dataFrom:
    - extract:
        key: PULUMI
