---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    image:
      repository: docker.io/eclipse-mosquitto
      tag: 2.0.15
    env:
      TZ: "Europe/Berlin"
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            primary: true
            port: 1883
            protocol: TCP
        externalTrafficPolicy: Cluster
        annotations:
          # external-dns.alpha.kubernetes.io/hostname: "mosquitto.${SECRET_DOMAIN}"
          io.cilium/lb-ipam-ips: "${VIP_MOSQUITTO}"
    persistence:
      data:
        enabled: true
        type: pvc
        mountPath: /mosquitto/data
        existingClaim: mosquitto-data
      config:
        enabled: true
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
        type: custom
        volumeSpec:
          configMap:
            name: mosquitto-config
