---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-config-v1
  namespace: default
  labels:
    app.kubernetes.io/name: &name baikal
    app.kubernetes.io/instance: *name
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-data-v1
  namespace: default
  labels:
    app.kubernetes.io/name: &name baikal
    app.kubernetes.io/instance: *name
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
