---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: thanos
      version: 12.8.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    query:
      enabled: true
      replicaLabels:
        - replica
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      ingress:
        enabled: true
        hostname: "thanos.${SECRET_DOMAIN}"
        ingressClassName: "nginx"
        pathType: Prefix
    existingObjstoreSecret: thanos-objstore
    queryFrontend:
      enabled: false
    bucketweb:
      enabled: true
      ingress:
        enabled: true
        hostname: "thanos-bucketweb.${SECRET_DOMAIN}"
        ingressClassName: "nginx"
        pathType: Prefix
    compactor:
      enabled: true
      ingress:
        enabled: true
        hostname: "thanos-compactor.${SECRET_DOMAIN}"
        ingressClassName: "nginx"
        pathType: Prefix
      persistence:
        enabled: true
        storageClass: local-path
        size: 10Gi
    storegateway:
      enabled: true
      ingress:
        enabled: true
        hostname: "thanos-storegateway.${SECRET_DOMAIN}"
        ingressClassName: "nginx"
        pathType: Prefix
      persistence:
        enabled: true
        storageClass: local-path
        size: 10Gi
    ruler:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
