---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 7.1.3
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  values:
    fullnameOverride: blackbox-exporter
    image:
      repository: quay.io/prometheus/blackbox-exporter
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: "blackbox.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
    config:
      modules:
        icmp:
          prober: icmp
          timeout: 15s
          icmp:
            preferred_ip_protocol: "ip4"
    serviceMonitor:
      enabled: true
      defaults:
        labels:
          release: prometheus
        interval: 1m
        scrapeTimeout: 30s
        module: icmp
      targets:
        - name: router-core
          url: 192.168.178.1
        - name: router-eg
          url: 192.168.178.2
        - name: router-og
          url: 192.168.178.6
        - name: repeater-kg
          url: 192.168.178.7
        - name: repeater-eg
          url: 192.168.178.4
        - name: repeater-og
          url: 192.168.178.5
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        add: ["NET_RAW"]
    prometheusRule:
      enabled: true
      additionalLabels:
        app: prometheus-operator
        release: prometheus
      rules:
        - alert: BlackboxProbeFailed
          expr: probe_success == 0
          for: 3m
          labels:
            severity: critical
          annotations:
            description: The host {{"{{ $labels.target }}"}} is currently unreachable
