---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pulumi-kubernetes-operator
  namespace: infra
spec:
  interval: 30m
  chart:
    spec:
      chart: pulumi-kubernetes-operator
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: pulumi
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: pulumi/pulumi-kubernetes-operator
      tag: 1.13.0
    serviceAccount:
      create: true
      name: pulumi-kubernetes-operator
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              group: rbac.authorization.k8s.io
              version: v1
              kind: Role
              name: pulumi-kubernetes-operator
            patch:
              - op: add
                path: /rules/0
                value:
                  apiGroups:
                    - source.toolkit.fluxcd.io
                  resources:
                    - gitrepositories
                  verbs:
                    - get
                    - list
                    - watch
