---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pulumi-kubernetes-operator
  namespace: infra
spec:
  interval: 30m
  chart:
    spec:
      chart: pulumi-kubernetes-operator
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: pulumi
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: pulumi/pulumi-kubernetes-operator
      tag: 1.13.0
