---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: mosquitto
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: docker.io/eclipse-mosquitto
      tag: 2.0.14
    env:
      TZ: "Europe/Berlin"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_MOSQUITTO_ADDR}"
        # externalIPs:
        #   - "${SVC_MOSQUITTO_ADDR}"
        externalTrafficPolicy: Local
    auth:
      enabled: false
    persistence:
      data:
        enabled: true
        type: pvc
        mountPath: /mosquitto/data
        existingClaim: mosquitto-data-v1
