---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: mosquitto
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    controller:
      labels:
        backup.home.arpa/backup-claim: &claimName "mosquitto-data-v1"
    image:
      repository: docker.io/eclipse-mosquitto
      tag: 2.0.14
    env:
      TZ: "Europe/Berlin"
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${SVC_MOSQUITTO_ADDR}"
    auth:
      enabled: false
    persistence:
      data:
        enabled: true
        type: pvc
        mountPath: /mosquitto/data
        existingClaim: *claimName
