---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-postgres-operator
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: "postgres-rw.database.svc.cluster.local"
        POSTGRES_USER: "{{ .POSTGRES_SUPER_USER }}"
        POSTGRES_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_URI_ARGS: ""
        POSTGRES_CLOUD_PROVIDER: ""
        POSTGRES_DEFAULT_DATABASE: "postgres"
  dataFrom:
    - extract:
        key: CLOUDNATIVE_PG
