---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ext-postgres-operator
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: ext-postgres-operator
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: postgres-operator
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/movetokube/postgres-operator
      tag: 1.2.5
    existingSecret: ext-postgres-operator
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        memory: 400Mi
