# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: influxdb-admin-secret
    namespace: default
stringData:
    admin-password: ENC[AES256_GCM,data:1xUFMCZx1LWPwlzxGEyHsA==,iv:rwIe7UJUtqjrep576TNl2ZMrcKPgy/HVRbQmLpSgWjc=,tag:uGWoXf1F/7MQDXuk7n4m3Q==,type:str]
    admin-token: ENC[AES256_GCM,data:kZzxy9ak3UUA5T2/TOJC3Q==,iv:b0F+urVGflEkAyc7yC+djFJ3VJVBHyoQUs2numRNvqg=,tag:wyZGh4MSBsqCCNbML7rvbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mjwvxuph2r4kvz8lkew4gvfj6xkgyps7mqj724y9akvdd99ljycsur2jrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNEhYaG9GbjJnc1BnUkNK
            TmdyaXNwcHNWY2kzdStpTjZwVUNrOEs5bEVVCmdCa0t3dUNFS1RYUWMwTGlZR0Fh
            V1owN1hBQmFCek5LcU5yZFlRa3M2Yk0KLS0tIEUxTGhhSW1tZSt4TEM0WFBGb29Z
            cUpySFF0WU9GUjBlV0pYSWFQbmYwdDQK3GA3cwJdYuYkNSDgD25YFPBuOqR/Z1WM
            Cp+B95VuP940vMb+KVqGz4DGJirR2hgLumR1BsfgDieKbekphx0zOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T02:21:24Z"
    mac: ENC[AES256_GCM,data:QsJGTC1G5bSsJLwYHNSphMS/nsxSub5xx94hlDfshAINdckVwCg35kE0AwWB3sui8j26e6htTC/K+YOcqviBM6cfPQQiRdh7n833PAnGhXW0cYnvugduIbVb2tN5lLhTzNMksxuqof/MOXXXaKVxlUa7FDVsEjcWdRY1NoSbju8=,iv:dsNulps1aMH/T7uQVBJL9/+AZquKUtv5FAfrt8L/Hio=,tag:XRvDjnvQbdX+fpcloXgMGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
