---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-dns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: coredns
      version: 1.19.8
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
  values:
    image:
      repository: quay.io/oriedge/k8s_gateway
      tag: v0.3.3
    serviceType: LoadBalancer
    service:
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/loadBalancerIPs: "${SVC_HOME_DNS_ADDR}"
    serviceAccount:
      create: false
      name: home-dns-cluster
    rbac:
      create: false
    isClusterService: false
    servers:
      - zones:
          - zone: .
            scheme: dns://
        port: 53
        plugins:
          - name: log
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: cache
            parameters: "300"
          - name: loop
          - name: local
          - name: prometheus
            parameters: "localhost:9153"
          - name: k8s_gateway
            parameters: "${SECRET_DOMAIN}"
            configBlock: |-
              resources Ingress
              ttl 10
              fallthrough
          - name: forward
            parameters: ". 1.1.1.1 1.0.0.1"
