---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_REDIS__PASSWORD: "{{ .REDIS_PASSWORD }}"
        AUTHENTIK_EMAIL__HOST: "{{ .EMAIL_HOST }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .EMAIL_USERNAME }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .EMAIL_PASSWORD }}"
        AUTHENTIK_EMAIL__FROM: "{{ .EMAIL_FROM }}"
  dataFrom:
    - extract:
        key: AUTHENTIK
    - extract:
        key: REDIS
