---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

