---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: atuin-server
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/atuinsh/atuin
              tag: 18.0.1
            args: ["server", "start"]
            env:
              TZ: "${TIMEZONE}"
              ATUIN_HOST: 0.0.0.0
              ATUIN_PORT: &port "8888"
              ATUIN_OPEN_REGISTRATION: "true"
              ATUIN_DB_URI:
                valueFrom:
                  secretKeyRef:
                    name: pg-atuin-server
                    key: POSTGRES_URL
            resources:
              requests:
                cpu: 10m
                memory: 30Mi
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          external.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.alpha.kubernetes.io/target: "dex.${SECRET_DOMAIN}"
        hosts:
          - host: "atuin.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - "atuin.${SECRET_DOMAIN}"
