---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: atuin-server
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/atuinsh/atuin
      tag: 17.0.1
    args: ["server", "start"]
    env:
      TZ: "${TIMEZONE}"
      ATUIN_HOST: 0.0.0.0
      ATUIN_PORT: &port "8888"
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI:
        valueFrom:
          secretKeyRef:
            name: pg-atuin-server
            key: POSTGRES_URL
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: "atuin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "atuin.${SECRET_DOMAIN}"
    # probes:
    #   liveness: &probe
    #     enabled: true
    #     custom: true
    #     spec:
    #       httpGet:
    #         path: /api/health
    #         port: *port
    #       initialDelaySeconds: 0
    #       periodSeconds: 10
    #       timeoutSeconds: 1
    #       failureThreshold: 3
    #   readiness: *probe
    #   startup:
    #     enabled: false
