---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      engineVersion: v2
      data:
        ADMIN_USER: "{{ .ADMIN_USER }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        ADMIN_EMAIL: "{{ .ADMIN_EMAIL }}"
  dataFrom:
    - extract:
        key: GRAFANA

