---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: github-receiver
  namespace: flux-system
spec:
  type: github
  events:
    - ping
    - push
  secretRef:
    name: github-webhook-token-secret
  resources:
    # cluster
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: home-kubernetes
      namespace: flux-system
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: cluster
      namespace: flux-system
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: cluster-apps
      namespace: flux-system
    # cluster-extra
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: home-kubernetes-extra
      namespace: flux-system
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: cluster-extra
      namespace: flux-system
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: cluster-extra-apps
      namespace: flux-system
    # pulumi
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: home-pulumi
      namespace: flux-system
