apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:eSgYNDoJRTzAl7Z5ySceUsUQjH11mdmg,iv:OSs8xqV29srcLGOO/XPIBZDXvBWYSxyoJHrDSa4/Fl0=,tag:UAl3fzOVIZPqQCo0CvdhyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14pz5aw6h2m05jezv8yasyvalm0sqzpgwxkd8pusve2xwdwm22auqd3qu54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSzNyb0YxTEs0cjBLTS9V
            OU1LMlRXQmdwaXpRck1UaHdPa2lNNUJMWFNJCkVNeDAyb3hrdzNGMWd4b2R0dWV5
            M1kxNGh2UWZZdG5FVEQwak9PMGNLUkEKLS0tIHN5aHJzakFJM0RKL052MEM1YVlm
            a292QmwxWkFGMDN6M1Bkclp3Zzcwcm8K7OOzPEXSBTQHgow7grw9F+w4O6XBKDAV
            CAYSbVMrTPCDazBr54Nvdau2mwbVivkptnQd+VFoCc2H9/g7Jbuziw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-26T16:24:07Z"
    mac: ENC[AES256_GCM,data:ZByuI+DFJqAlrrnbDmByX3e/1Zi48NOPK5ClGQn13r0BmT3JmoKFPvu7wuVwko+rR1Nttv+kzfjDYWn8VlUcihKrKFnGAyPER99TwC+/szGtH2PJH0Ff4ZmkHgCZNeByOfwCJa0lVrmPVepHy3F5KiuP/AftB0GF8KRWBwOrEm0=,iv:/FZ9NmOskXinS3MJdEQdJNzt5owU1BWH7l3tM6JLSv4=,tag:ZbhENWdy7oBcx48+fSn46g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
