---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2023.6.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      AUTHENTIK_REDIS__HOST: redis.database.svc.cluster.local
      AUTHENTIK_REDIS__DB: 2
      AUTHENTIK_POSTGRESQL__SSLMODE: disable
      AUTHENTIK_COOKIE_DOMAIN: "${SECRET_DOMAIN}"
    envFrom:
      - secretRef:
          name: authentik-secret
    envValueFrom:
      AUTHENTIK_POSTGRESQL__HOST:
        secretKeyRef:
          name: pg-authentik-user
          key: HOST
      AUTHENTIK_POSTGRESQL__NAME:
        secretKeyRef:
          name: pg-authentik-user
          key: DATABASE_NAME
      AUTHENTIK_POSTGRESQL__USER:
        secretKeyRef:
          name: pg-authentik-user
          key: LOGIN
      AUTHENTIK_POSTGRESQL__PASSWORD:
        secretKeyRef:
          name: pg-authentik-user
          key: PASSWORD
    prometheus:
      serviceMonitor:
        create: true
        interval: 30s
        scrapeTimeout: 3s
      rules:
        create: false
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: &host "auth.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
