---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: authentik
  namespace: default
spec:
  database: authentik
  dropOnDelete: false
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: authentik-user
  namespace: default
spec:
  role: authentik
  database: authentik
  secretName: pg
  privileges: OWNER

