# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:JmYLkqzNNo5nkxmk+EgoIM0DZvXD2comwuFj9YeoXx1oIyT3wIbL/ylaEKRUUjAjndutq494L/yXMxSXC8XD5A7n7Qu9UuPsaubXBtjhlHpTlWGTLAK/qk/lrk9Qow1kb4wSh9BjzoFw1vdlXSrRipOSyWhHVpmCApETbJH6afYrZx1RtPSbXioT+vg9gA==,iv:zSSWNbBPMhtF2Nl33F71P4jmjS1hEZFjokwK6qv6hII=,tag:3m+qtWnNOB2P7/y2zXt5Lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mjwvxuph2r4kvz8lkew4gvfj6xkgyps7mqj724y9akvdd99ljycsur2jrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZlRTcjJ6U2E4VGptK3RU
            SkZNSDU3MC94YnJPc1RQRTJWbW95VDk3WWg4CnM2bmZOeFp6L2JqNmZlRG9FdktR
            Zzh3U0twU25rVnZITlo2R0VYUFlYNFUKLS0tIFpwenJtTWw5VWVQbHk2dmFkRUxu
            SHV0U09TV1UvN1NCeXZsT09JcWNjcmMKRk6MojJyGY4HPjerRgyX+jDWNMlWMSZt
            0hqI0TKIzJPs7x2tp1HVRnScbv6T1bkCGUEe9tAfGhtDOEZQLZj/jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-08T11:16:45Z"
    mac: ENC[AES256_GCM,data:0hqLw5Ad/4XViySiedkO/vDJj0822U+u4kseCGlisldezNEHyFp3OyE/DKI/igD2b2RaigRkGT8iFnuX5ttU86hcpDQDBz5/lobYZxdO0XjGdFZFKFTTFUtDWTLbTSuc0MrQYG8YfY40yPiF8Qa6hT3Q9Z8ZmDkFml+16Hy8xsY=,iv:zIbECEgVYnmP7StZe42TH63hJSxkXSVfL/OfuNzzXEM=,tag:egM24Z8zc695B7NW4lBiMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
