---
- name: Upgrade all system packages
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_upgrade
  retries: 3
  until: apt_upgrade is success

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ setup_packages_install | default([]) }}"
    update_cache: true
    install_recommends: false
  register: apt_install_common
  retries: 3
  until: apt_install_common is success

- name: Create ~/git folder
  become_user: "{{ ansible_user }}"
  ansible.builtin.file:
    path: "{{ setup_home_dir }}/git"
    state: directory
    mode: '0755'
