---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config-v1
  namespace: home
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
