---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: default-backup
  namespace: longhorn-system
spec:
  cron: "47 2 * * *"
  task: "backup"
  groups:
    - default
  retain: 5
  concurrency: 2

