---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firefly-iii
  namespace: default
spec:
  ingressClassName: "nginx"
  annotations:
    auth.home.arpa/enabled: "true"
  rules:
    - host: "firefly.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: firefly-iii
                port:
                  number: 8080
