---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-uploads-pvc
  namespace: default
  labels:
    app.kubernetes.io/name: &name firefly-iii
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-db-pvc
  namespace: default
  labels:
    app.kubernetes.io/name: &dbname firefly-iii-db
    app.kubernetes.io/instance: *dbname
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 15Gi
