---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: calibre-web
      version: 8.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: linuxserver/calibre-web
      tag: 0.6.18
    env:
      TZ: Europe/Berlin
      DOCKER_MODS: "linuxserver/calibre-web:calibre"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "calibre-web.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config-v1
      nfs-nas-media:
        enabled: true
        type: nfs
        server: "${NAS_ADDR}"
        path: /volume1/ebooks/calibre-web
        mountPath: /data
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
