---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/linuxserver/calibre-web
      tag: version-0.6.18
    env:
      TZ: Europe/Berlin
      DOCKER_MODS: "linuxserver/calibre-web:calibre"
      PUID: "1001"
      PGID: "1001"
    service:
      main:
        ports:
          http:
            port: 8083
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "calibre-web.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config-v1
      nfs-nas-media:
        enabled: true
        type: nfs
        server: "${NAS_ADDR}"
        path: /volume1/ebooks/calibre
        mountPath: /data
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
