---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config-v1
  namespace: default
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
