---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-config-v1
  namespace: default
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
