---
os_timezone: "Europe/Berlin"
os_packages_install:
  - apt-transport-https
  - arptables
  - ca-certificates
  - curl
  - ebtables
  - gdisk
  - hdparm
  - htop
  - iputils-ping
  - ipvsadm
  - kitty-terminfo
  - lvm2
  - nano
  - net-tools
  - nfs-common
  - nvme-cli
  - ntpdate
  - open-iscsi
  - psmisc
  - smartmontools
  - socat
  - software-properties-common
  - unzip
os_packages_remove:
  - apparmor
  - apport
  - byobu
  # - cloud-init
  # - cloud-guest-utils
  # - cloud-initramfs-copymods
  # - cloud-initramfs-dyn-netconf
  - friendly-recovery
  - landscape-common
  - lxd-agent-loader
  - ntfs-3g
  - popularity-contest
  # - snapd
  - sosreport
  - ubuntu-advantage-tools
