---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${PVC}-restore-snapshot
  namespace: ${NAMESPACE}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: restore
          image: ghcr.io/onedr0p/kopia:0.11.3@sha256:2ae9ede0edac68c09d517abd71fa12c96efcf19f27ce7ffca968cebb10ed0e2d
          env:
            - name: KOPIA_PASSWORD
              value: "${KOPIA_PASSWORD}"
          command:
            - /bin/bash
            - -c
            - |-
              shopt -s dotglob
              echo "[01/04] Connect to repo ..."      && kopia repo connect filesystem --path=/data --override-hostname=cluster --override-username=root
              echo "[02/04] Remove previous data ..." && rm -rf /data/${PVC}/*
              echo "[03/04] Restore snapshot ..."     && kopia snap restore "${SNAPSHOT}" /data/${PVC}
              echo "[04/04] Disconnect from repo ..." && kopia repo disconnect
          volumeMounts:
            - name: ${PVC}-data
              mountPath: /data/${PVC}
            - name: snapshots
              mountPath: /data
          securityContext:
            privileged: true
      volumes:
        - name: ${PVC}-data
          persistentVolumeClaim:
            claimName: ${PVC}
        - name: snapshots
          nfs:
            server: 192.168.178.40
            path: /volume1/backups/kopia
