---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template-extra
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: app-template-extra-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.11.3
    envFrom:
      - secretRef:
          name: paperless
    service:
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          auth.home.arpa/enabled: "true"
        hosts:
          - host: "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        mountPath: /usr/src/paperless/data
        existingClaim: paperless-data
      media:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        mountPath: /usr/src/paperless/media
        existingClaim: paperless-media
      export:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        mountPath: /usr/src/paperless/export
        existingClaim: paperless-export
      # consume:
      #   enabled: true
      #   type: nfs
      #   server: "${NAS_ADDR}"
      #   path: "/volume1/paperless/consume"
      #   mountPath: /usr/src/paperless/consume
    postgresql:
      enabled: true
      nameOverride: postgresql
      # image:
      #   repository: bitnami/postgresql
      #   tag: 13.8.0
      auth:
        username: paperless
        database: paperless
        existingSecret: paperless-postgresql
      primary:
        enabled: true
        persistence:
          enabled: true
          existingClaim: paperless-postgresql
    redis:
      enabled: true
      nameOverride: redis
      # image:
      #   repository: bitnami/redis
      #   tag: 6.2.7
      architecture: standalone
      auth:
        enabled: false
      persistence:
        enabled: false
