# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: paperless
    namespace: default
stringData:
    TZ: ENC[AES256_GCM,data:eHpeU8sj4vRYcjzNLg==,iv:NXIIZUYX5a9iH0569UOM+71dmJNDrThjgJWnwJ+4Qd4=,tag:6a1kLDXYn5Z5bIeHRdvZcw==,type:str]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:M07tVvFHVmBRR3qq8U/dL62osWjouWdb0TRYtw==,iv:p6H++37nejdlL02tvRJCjAQnfL26ibqVYmmsuQ89kVw=,tag:4pBKYhmeT0tnmA4lh2CGCQ==,type:str]
    USERMAP_UID: ENC[AES256_GCM,data:EWNXzg==,iv:mbcrphjL0JtIFJGa2TsZCc5C3RfBwLzvno3FhDAmeRk=,tag:FprGI57f1DJ6hqLusmz2Rg==,type:str]
    USERMAP_GID: ENC[AES256_GCM,data:MGH+bA==,iv:tCqdiqySVpyxISiQn/G5rgQlSL+VG0iSA4axzs7kLe8=,tag:8YY38JYQStQNynyzSmfjHg==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:/qp7npY=,iv:zKMAgXBVVkwpcc60za9Spubw84JCQ50rXLxZxVXyWl8=,tag:khcSHKsko0qNpKn4iCbscA==,type:str]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:QqGL6iMaHXV64z43RBI=,iv:vHqyGacGofYm0g8usy1CxjmjUX2hclAKjMKTcFTy/Ko=,tag:Dr+a/HwYPTJGE769czK5YQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:qes9hybkf+iKM19JEFktJw==,iv:mgdVdzTw6gmCOkVqAxogvfKS6iq9nd6MkAAVxcHV7Q0=,tag:2xW7ZgXRJLHOv+5z8kReWA==,type:str]
    PAPERLESS_DBHOST: ENC[AES256_GCM,data:l+saLE62Y1x594OcA1TwyoLbGN4=,iv:K3bn9REt74CblbbEXCPxy4GooLvyzQjvVu6C45Jpqq0=,tag:DKOp0CJQLjwXbN6xYRDB3g==,type:str]
    PAPERLESS_DBPORT: ENC[AES256_GCM,data:y6CCLg==,iv:f5kRI3kWbZY0yok6a0UX/+V2si8AkeBX3lnzKhdauig=,tag:MT/puhidENhHXdujLbD1Ng==,type:str]
    PAPERLESS_DBNAME: ENC[AES256_GCM,data:QPg07ivMtdDs,iv:SQz9c1BA/QDnJ499+Htupf0iZ+Y2A6nyqwkx+Ge2fZ4=,tag:zgfZrvZ2Pj6tGiGVBzoR4Q==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:G9ZyOAF37894,iv:yE4M+Mnx446CBFCLQ48BTdW19HvcdP/aGBA/waMcgV0=,tag:FvcZvjDOmPsyIN82OyhXMw==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:q4vpJL8tIWk8MTdVvxdDtNszxrc=,iv:iAuz9lTPATFpoGign8CAWxSCBiefNBHI514o/prftQs=,tag:unfQvskSz017kA6qX3l+yA==,type:str]
    PAPERLESS_DBSSLMODE: ENC[AES256_GCM,data:rgAA0QJt,iv:1VukvD5HhKn43vTVjNSxGFaVi63dr8Ed+ahvUf2pwOs=,tag:7U7HxzAdkqMJLmUPf6VRZg==,type:str]
    PAPERLESS_FILENAME_FORMAT: ENC[AES256_GCM,data:g8/e4cPgRLGjT/W36+4acIu0wkTP6QayQya0j2KFYFKijW2uRvgDQ10AX6AyQTnDBfOth4VJq2VKRdnk5ZXaE7F6dWNIga9CAAM=,iv:YdDfHqjz4DuhcCBVxESJNWTO/nsOtUSgFJnfpBgtLcM=,tag:kD5BFxYQ9FXuMblgKnG1BA==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:IU6cfcbKmVsRgm2yRUZIaFz2YWzVvCQeFt1VC++4uZA=,iv:0ZRnlnfWjSLzjOLSQ3VaW5/RKyX21mJW0KkUks2wS+E=,tag:TVgC0DFS1nQJU1QejWbGtA==,type:str]
    PAPERLESS_URL: ENC[AES256_GCM,data:ZORlFgEEqcoxVpP9gctn9JO2uT8s9l/PjV4=,iv:cesG90rIQ/9cVYve0gzAA0cZVs8i6BYL51GbfKldCDc=,tag:TF61au1d3hhJgzFw/WZCLw==,type:str]
    PAPERLESS_OCR_LANGUAGE: ENC[AES256_GCM,data:Q26n,iv:SQQG/7Zr6AY7yGYh1cbxXpeqOqa145/BAZVimN2qxtY=,tag:GygRHAU4MmQ0wbuta9B2EA==,type:str]
    PAPERLESS_OCR_CLEAN: ENC[AES256_GCM,data:MjFx5M8=,iv:7fOOiqgoP1FYeqP6wmoNCznfjjC8Ufvtsi+QcGcfdTA=,tag:YUZlUz2S1X9yH00vHYMnHg==,type:str]
    PAPERLESS_OCR_DESKEW: ENC[AES256_GCM,data:uhtE6Vw=,iv:dHn9Z26W4bmN4O64/OPu4JuuIezCpX8pVjGMyK8G4sI=,tag:6tadO0k6goNqb51ZsSUilA==,type:str]
    PAPERLESS_OCR_ROTATE_PAGES: ENC[AES256_GCM,data:++SSmFk=,iv:43ubJu5j3uZgbC7qOSPprDfMG2iremhGefZxPqD/JGg=,tag:XoEHpfcdORDU8LH7USGhgw==,type:str]
    PAPERLESS_TASK_WORKERS: ENC[AES256_GCM,data:8Q==,iv:Trlc3aYuXrk+Z3kyaMtbnNM/4vP7ghe6kxN6nvjrhPs=,tag:3RhCzdMOjyPbhnGIEqILEA==,type:str]
    PAPERLESS_THREADS_PER_WORKER: ENC[AES256_GCM,data:EQ==,iv:eDGY5dLtOecfu4fH5nl8bQNoDBT1oG+fdRiZC0mFElc=,tag:jGRCKfOtpnoRBYbH/Ef60Q==,type:str]
    PAPERLESS_TIME_ZONE: ENC[AES256_GCM,data:QUnnvrCW68FMUroFmg==,iv:d74E/oNEHdbTZ0EzVTmy6j4WRkcyylFrR0b1z2JYr4Q=,tag:fWLhGNsNo1pjiqBVFShcnA==,type:str]
    PAPERLESS_CONSUMER_ENABLE_BARCODES: ENC[AES256_GCM,data:IHktLg==,iv:dNuXM32eufSkaH8qhP7ddLKGt20/jSuVR4jLrswa6Q8=,tag:yD5sc1pyq4YLSVTB8k2Nig==,type:str]
    PAPERLESS_CONSUMER_BARCODE_STRING: ENC[AES256_GCM,data:/A3zXUQZ,iv:zUQX1+9iw8vir13gbpe7MiGkjN/f6+rFfBpkcJNHo8s=,tag:YaR9eWkobYA55IUGPhHo+A==,type:str]
    PAPERLESS_FILENAME_DATE_ORDER: ENC[AES256_GCM,data:7r92,iv:Gr8wec2odYB6iph5yM8dEmEzfed+JMScmArWOX1b3wk=,tag:a0T5hN73T+nby6vzJ/9tgQ==,type:str]
    PAPERLESS_IGNORE_DATES: ENC[AES256_GCM,data:UWx0SCX5yXQ4BQ==,iv:ZH+fvEENTXfCNjf/ukphUG4GXugXuJ87gKrBARqlvhg=,tag:9iS2gIdIIQT9FyTjtaIZ+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mjwvxuph2r4kvz8lkew4gvfj6xkgyps7mqj724y9akvdd99ljycsur2jrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySVBoTm13ZU53K2xvYTZU
            by8xTm9uTXZQWTM4RW13U0lML0paNUF6SVFZClZndFpGT25QNXZzcjUzdzFReDlN
            WFI2aEJJNXhFMmttcVdFM2M0NHZHVE0KLS0tIGdPbnJUS1dhRjAxVk9DR3VrL3dK
            VnNBMWNVNzk0U1FhSFJJUU1wckI1NXMK+cLlX6k/hpUbGNLLpfwiU59cMFnXqr0F
            9GdhXNarf6XNLwa5fQoRyZUiUZ0kG1tqUUWPfTKc4AkkVipt/lAwSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-30T15:11:30Z"
    mac: ENC[AES256_GCM,data:hEoFhq/NNpMPwDV/9gyPyBQwF0Yww0dtyVeieXesECOmlsGhkWvfAjrU9/HYXVHJFmm1wyGoj3tEUNopIvm4Q9l6VxG+WdjF0ZCC+tpJ620cp0wTZhxM65AiCzbp1nfEtS9p7yrIexv07hk6MFPVXaE++YFNqFxHk44MR7JJUMw=,iv:LNAzIlOZqeezjo2Hk964g3k2XyGEKdQxuUUMLAu/wdI=,tag:6ECV15AcnUYci3Qtoyqq0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
