---
- name: Enable iscsid daemon
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: iscsid.service
    state: started

- name: Increase max_user_watches
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present
    sysctl_file: /etc/sysctl.d/98-kubernetes-fs.conf

# - name: Increase max_user_instances
#   ansible.posix.sysctl:
#     name: fs.inotify.max_user_instances
#     value: "512"
#     state: present
#     sysctl_file: /etc/sysctl.d/99-max_user_instances.conf

- name: Disable swap at runtime
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable swap on boot
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none

# - name: Set journald SystemMaxUse
#   ansible.builtin.lineinfile:
#     path: /etc/systemd/journald.conf
#     regexp: '^SystemMaxUse'
#     line: SystemMaxUse=128M
#     state: present
