---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: external-dns-secret
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: CLOUDFLARE
        property: API_TOKEN
