---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: external-dns-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        api-token: "{{ .API_TOKEN }}"
  dataFrom:
    - extract:
        key: CLOUDFLARE
