apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:ErsQCl1PT90S0XSOhe8/4c4Wfjl6JFjUQftDt7oBY1V8fQxstyb6wQ==,iv:Ez+zPL4+baAAWydlCHLAD9PY9fBzYbbiuwUCmlmSxdk=,tag:n9U84bpWLvJnCNOTC+iN3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14pz5aw6h2m05jezv8yasyvalm0sqzpgwxkd8pusve2xwdwm22auqd3qu54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dlduTGoxZjN4K2NRZWhY
            eExWSkNETWtFT0V0ektNMURVRElzVXM5UEhNCjdsbWJlU3dKclZ6V1NET0pJRXV0
            VXBmVDVkcjhHVDRMWlVaK1hVMHkzdVkKLS0tIDFKQURDdmYwNkhzL255ZkNXc3JQ
            NDlrUjk2SVU0T0xHN1g0RHZuTktsSjAKZdX6uGg1ShPreVWtVommGvAZfvhoANdJ
            Ve3cdxPbAzhkAkQEqyBaLk0AXvpksXV1lAUKEcL0A8lc1U7OciJ95Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-26T17:05:23Z"
    mac: ENC[AES256_GCM,data:jjI0FvRDCpndTSru1g5BjN2fqykGHcdV2yYBXy6UTkaDLO6P7L6S7s3ZQJp9UPDcmERYjV/dKLLSeC1fV8BZUlIAlTyZd17uxmE3qJ76LlrzN6gh0E8vH0XRhVXUYsvNOphq9klaE6bKnwHV7CE6VTp5z2eGZOl9W27FiKhvWcA=,iv:nGD7ewBXVnAQOb93jXRTg8im+TuFXmYv3CbXlZOMhMg=,tag:2zJ4sFTEdnG4/InszmAm/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
