---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.1
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
  values:
    image:
      repository: influxdb
      tag: 2.3.0-alpine
    fullnameOverride: influxdb
    adminUser:
      organization: influxdata
      bucket: default
      user: admin
      retention_policy: 0s
      existingSecret: influxdb-admin-secret
    persistence:
      enabled: true
      useExisting: true
      name: influxdb-data-v1
    ingress:
      enabled: true
      className: nginx
      hostname: "influxdb.${SECRET_DOMAIN}"
      path: /
    pdb:
      create: false
