---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./authentik/ks.yaml
  - ./esphome/ks.yaml
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./s3-mirror/ks.yaml
  - ./tasmoadmin/ks.yaml
  - ./zigbee2mqtt/ks.yaml
