---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tasmoadmin
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: docker.io/raymondmm/tasmoadmin
      tag: v1.7.0
    nameOverride: tasmoadmin
    env:
      TZ: Europe/Berlin
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-local-only@kubernetescrd"
        hosts:
          - host: "tasmoadmin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: tasmoadmin-data-v1
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 400Mi
