---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tasmoadmin
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: docker.io/raymondmm/tasmoadmin
      tag: v1.7.0
    nameOverride: tasmoadmin
    env:
      TZ: Europe/Berlin
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            port: 80
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${SVC_TASMOADMIN_ADDR}"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "tasmoadmin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: tasmoadmin-data-v1
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 400Mi
