---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tasmoadmin
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    controller:
      labels:
        backup.home.arpa/backup-claim: &claimName "tasmoadmin-data-v1"
    image:
      repository: docker.io/raymondmm/tasmoadmin
      tag: v1.7.0
    nameOverride: tasmoadmin
    env:
      TZ: Europe/Berlin
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: "networking-local-only@kubernetescrd"
        hosts:
          - host: "tasmoadmin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: *claimName
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 400Mi
