---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasmoadmin-data-v1
  namespace: home
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
