# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:plrr5S4=,iv:FzcNforc4ENmin+mzVQoZFCYL9m0DIyFzkalS/sjKLY=,tag:Re055JnrxmFsXmk9wtKECA==,type:str]
    ADMIN_PASS: ENC[AES256_GCM,data:tgeXnJ0AWPclj0BGOnnSEA==,iv:FaRRMGnArzQgCs74e5nXp4tRHrKc1aTZ2pzvJE4FYEg=,tag:PZsp0PfpDzm3f0qbz6m3Ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mjwvxuph2r4kvz8lkew4gvfj6xkgyps7mqj724y9akvdd99ljycsur2jrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6c1JTb3ZaY1dyakZENFNl
            ZU81ZXZYYVA4Zm1DbG9PbE5MT2taK0N2ZFU0Cmh4M3R2MmZNQytZMUpBTTdnUXYr
            ZE8yVE4vZzlXelFnVnFwZVB4THM5Z2sKLS0tIFhERTNUcXkzeWZ0Tnc3djRQQ1NS
            MTVxRVlib0V0RE01UUliWUthMm92aFUKXVXOEMgUbvXdgdB0fnV7avIeDBWq8fBU
            o/rIPM4UtbiSDmlSywZvD0k8nIsFfaSUxOOJCAohhqYZNlcjp1s9qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-07T22:26:57Z"
    mac: ENC[AES256_GCM,data:Kwe9myz/TropBHlnsMmhqZBoeA0mDLqDsxfB/cvHKKyB0YYTkywYeuELcImdG9cp/rJOrkFDoR9udsCJOU/9SW6ZVPTjoDucqXdY0gKQ2HmlHrVoLkiHtW82McRTaF4E9msByUHsZUWKxCJhEh0kgDn0YnW1E8MoTCK5kjQNNpk=,iv:hDE79Tz9xayEL/YyCHkqrWWBNrBAQaIOrosRdCn98a0=,tag:y+y9p7qNBZVLfpVtjt111g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
