---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.2.5
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    controller:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPort:
        enabled: true
        ports:
          http: 80
          https: 443
      extraEnvs:
        - name: TZ
          value: "Europe/Berlin"
      kind: DaemonSet
      service:
        enabled: false
      config:
        # custom-http-errors: |-
        #   400,401,403,404,500,502,503,504
        # forwarded-for-header: "X-Forwarded-For"
        # ssl-protocols: "TLSv1.3 TLSv1.2"
        # use-forwarded-headers: "true"
        brotli-level: "6"
        client-body-buffer-size: "100M"
        client-body-timeout: "120"
        client-header-timeout: "120"
        enable-brotli: "true"
        enable-real-ip: "true"
        force-ssl-redirect: "true"
        gzip-level: "6"
        hsts-max-age: "31449600"
        keep-alive-requests: "10000"
        keep-alive: "120"
        log-format-escape-json: "true"
        log-format-upstream: '{"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time, "method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent"}'
        proxy-body-size: "100M"
        proxy-read-timeout: "3600"
        proxy-real-ip-cidr: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,100.64.0.0/10"
        proxy-send-timeout: "3600"
        use-gzip: "true"
        use-http2: "true"
        use-proxy-protocol: "true"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: networking
          namespaceSelector:
            any: true
      extraArgs:
        default-ssl-certificate: |-
          networking/${SECRET_DOMAIN/./-}-tls
