---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.2.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    controller:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPort:
        enabled: true
        ports:
          http: 80
          https: 443
      extraEnvs:
        - name: TZ
          value: "Europe/Berlin"
      kind: DaemonSet
      service:
        enabled: false
      config:
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        # custom-http-errors: |-
        #   400,401,403,404,500,502,503,504
        enable-brotli: "true"
        forwarded-for-header: "X-Forwarded-For"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: "100M"
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-forwarded-headers: "true"
        force-ssl-redirect: "true"
        use-proxy-protocol: "true"
      extraArgs:
        default-ssl-certificate: |-
          networking/${SECRET_DOMAIN/./-}-tls
