---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.2.5
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    controller:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPort:
        enabled: true
        ports:
          http: 80
          https: 443
      extraEnvs:
        - name: TZ
          value: "Europe/Berlin"
      kind: DaemonSet
      service:
        enabled: false
      config:
        # custom-http-errors: |-
        #   400,401,403,404,500,502,503,504
        enable-real-ip: "true"
        proxy-real-ip-cidr: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,100.64.0.0/10"
        use-proxy-protocol: "true"
        # ssl-protocols: "TLSv1.3 TLSv1.2"
        brotli-level: "6"
        client-body-buffer-size: "100M"
        client-body-timeout: "120"
        client-header-timeout: "120"
        enable-brotli: "true"
        force-ssl-redirect: "true"
        # forwarded-for-header: "X-Forwarded-For"
        gzip-level: "6"
        hsts-max-age: "31449600"
        keep-alive-requests: "10000"
        keep-alive: "120"
        proxy-body-size: "100M"
        # use-forwarded-headers: "true"
        use-gzip: "true"
        use-http2: "true"
      extraArgs:
        default-ssl-certificate: |-
          networking/${SECRET_DOMAIN/./-}-tls
