---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops-secret
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: cluster-user-auth
    template:
      engineVersion: v2
      data:
        username: admin
        password: "{{ .WEAVE_GITOPS_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: WEAVE_GITOPS
