---
- name: Fetch service account for home-dns-external
  ansible.builtin.set_fact:
    dns_service_account_raw: "{{ lookup('kubernetes.core.k8s', kubeconfig=playbook_dir + '/../../../cluster/kubeconfig', namespace='networking', kind='ServiceAccount', resource_name='home-dns-external') }}"

- name: Extract service account token from service account
  ansible.builtin.set_fact:
    dns_service_account_token: "{{ dns_service_account_raw | json_query('secrets[*].name | [0]') }}"

- name: Fetch CA
  ansible.builtin.set_fact:
    dns_certificate_authority_raw: "{{ lookup('kubernetes.core.k8s', kubeconfig=playbook_dir + '/../../../cluster/kubeconfig', namespace='networking', kind='Secret', resource_name=dns_service_account_token) }}"

- name: Extract CA Cert from CA
  ansible.builtin.set_fact:
    dns_certificate_authority: '{{ dns_certificate_authority_raw | json_query(''data."ca.crt"'') }}'

- name: Extract CA Token from CA
  ansible.builtin.set_fact:
    dns_certificate_authority_token: "{{ dns_certificate_authority_raw | json_query('data.token') | b64decode }}"

- name: Create kubeconfig
  ansible.builtin.copy:
    dest: "{{ kubeconfig_dest_dir }}/kubeconfig"
    content: |
      ---
      apiVersion: v1
      kind: Config
      clusters:
      - name: home
        cluster:
          certificate-authority-data: "{{ dns_certificate_authority }}"
          server: "https://{{ cluster_addr }}:6443"
      contexts:
      - name: home
        context:
          cluster: home
          user: home-dns-external
      users:
      - name: home-dns-external
        user:
          token: {{ dns_certificate_authority_token }}
      current-context: home
    mode: 0755

- name: Copy kubeconfig to local directory
  ansible.builtin.fetch:
    src: "{{ kubeconfig_dest_dir }}/kubeconfig"
    dest: "{{ playbook_dir }}/../../../cluster/kubeconfig-homedns-external"
    flat: true
