---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ingress
spec:
  generateExistingOnPolicyUpdate: true
  rules:
    - name: add-default-traefik-entrypoint
      match:
        any:
          - resources:
              kinds:
                - Ingress
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              +(traefik.ingress.kubernetes.io/router.entrypoints): "websecure"
    - name: add-default-external-dns-target
      match:
        any:
          - resources:
              kinds:
                - Ingress
              annotations:
                external-dns/is-public: "true"
      # exclude when explicit target set
      exclude:
        any:
          - resources:
              kinds:
                - Ingress
              annotations:
                external-dns.alpha.kubernetes.io/target: "*"
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              +(external-dns.alpha.kubernetes.io/target): "ipv4.${SECRET_DOMAIN}"
