# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:LgJfoRgE5/o7M7NM25g+6mfn/B7gNn9iKUdtBzQX4mZv8H0VuKjpvw==,iv:J8mrvHG7QFoFBp/Uxc5+0nwNO7RqKkvFHKrWC3N3G6Q=,tag:wCgY6F+kKGX18UQ+x3jTGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mjwvxuph2r4kvz8lkew4gvfj6xkgyps7mqj724y9akvdd99ljycsur2jrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbTByQzNxWVFuc21YaUNT
            cktib0RKOFJxRkN6NU5yL2pyRVRMUWJTb1RBCkQvVWFNa3MzM1k1cE8wcUFRcHY1
            dWhOMXQvMzdBZjZOdXIyMk1Qcm0rNFEKLS0tIDRHME5xcmdBZng3QXdwdUlqVkVD
            SXV6VHZPVXh4Y1dkcEJ3cXlqVWZWNEUKOV5EmZPfabCFb5Dj2WJsj6TpwQ7lKC4x
            l9jCwLiajUERd1VEc1Mp2MLkSVwnqGywQIrgBcyvcbWiTkAP8fxhIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-10T20:49:06Z"
    mac: ENC[AES256_GCM,data:emPJ0YVZS36g0+kuUUVolV7msroiIbixqeToAprpfVptaOhhToUZA8tXbINp4MHEX29qgpYuRNa4fvEkBbRBHBXKYVB5FIIS1nnYpj3GXa4CU2te/TUwCbVzJ5HTbqPWwX1qgCBPTlbKYXQCdNbLg9LNd1Q2oVaKS6GAoCnfXS8=,iv:Tx/wzMqyzf1g0EggC03HTEth7kCleMfu9NtbVxWr8oI=,tag:rAhe4Y2b5fa3aqajBIxwBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
