---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: authelia
      version: 0.8.38
      sourceRef:
        kind: HelmRepository
        name: authelia-charts
        namespace: flux-system
  values:
    domain: "${SECRET_DOMAIN}"
    ingress:
      enabled: true
      annotations:
        external.home.arpa/enabled: "true"
      className: nginx
      subdomain: auth
      tls:
        enabled: false
    pod:
      kind: Deployment
      replicas: 1
      strategy:
        type: Recreate
      env:
        - name: TZ
          value: Europe/Berlin
      resources:
        requests:
          memory: 200Mi
          cpu: 150m
    configMap:
      enabled: true
      authentication_backend:
        # disable_reset_password: true
        ldap:
          enabled: false
        file:
          enabled: true
          path: /config/users_database.yml
          password:
            algorithm: sha512
            iterations: 50000
            salt_length: 16
      access_control:
        default_policy: deny
        rules:
          - domain: "*.${SECRET_DOMAIN}"
            policy: one_factor
            subject:
              - "group:admins"
      session:
        expiration: 4h
        inactivity: 30m
        remember_me_duration: 1M
        redis:
          enabled: false
      storage:
        local:
          enabled: true
          path: /config/db.sqlite3
        mysql:
          enabled: false
        postgres:
          enabled: false
      notifier:
        disable_startup_check: true
        filesystem:
          enabled: true
          filename: /config/notification.txt
        smtp:
          enabled: false
    secret:
      existingSecret: authelia-secrets
    persistence:
      enabled: true
      existingClaim: authelia-data-v1
