---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-data-v1
  namespace: default
  labels:
    app.kubernetes.io/name: &name authelia
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
