---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template-postgres
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: app-template-extra-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/miniflux/miniflux
      tag: 2.0.45
    env:
      TZ: "Europe/Berlin"
    envFrom:
      - secretRef:
          name: miniflux-secret
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external.home.arpa/enabled: "true"
        hosts:
          - host: "miniflux.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    postgresql:
      enabled: true
      nameOverride: postgresql
      auth:
        username: miniflux
        database: miniflux
        existingSecret: miniflux-postgresql-secret
      primary:
        enabled: true
        persistence:
          enabled: true
          existingClaim: miniflux-postgresql-v1
    resources:
      requests:
        memory: 150Mi
        cpu: 200m
      limits:
        memory: 400Mi
