---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Berlin"

  COREDNS_ADDR: "10.43.0.10"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"

  NAS_ADDR: "192.168.178.40"

  NODE_CIDR: "192.168.178.0/24"
  KUBE_VIP_ADDR: "192.168.178.250"
  VIP_K8S_GATEWAY: "192.168.178.249"
  VIP_INGRESS: "192.168.178.248"
  VIP_HOME_ASSISTANT: "192.168.178.247"
  VIP_POSTGRES: "192.168.178.246"

  VIP_MOSQUITTO: "192.168.178.212"
