---
- name: Install haproxy package
  ansible.builtin.apt:
    name:
      - haproxy
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600

- name: "Create haproxy configuration"
  ansible.builtin.template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - restart-haproxy
