# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:FBLg0UQOonc=,iv:7ChNYzvn9trprbZzCNPWHEEZTegKcUJaj3V6cbYqyOo=,tag:fCC6YD0frThSCfUssLaFnA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:0mCg+K+5qTZE0CXuHBw9FL9ccFmN,iv:3G65Gu+8YIO20wonCqBwifNPoYfggivgIC7+CEJCeiA=,tag:kCUc6N3ED0Gj4j6XneP1Qw==,type:str]
    SECRET_DISCORD_WEBHOOK_HOMELAB: ENC[AES256_GCM,data:ug0VmBqXsurPImqU73wIpcqQXA58GJ6QvCBJRnu4VpRkvRjKGIQvieS8GiyaVpt+2MXnK/c8nVr2JHKcdfr1Kfm6GWalbhMU4vXISav5IfwPdoHP+0AUk/t66GxGOb3Y1Vh3bGGzKBMH8z3dQM95RX2e5A2TVgee3OJwqOnA,iv:JtlrNzgaGE2yT1TrCOn/WtO47RMeQaDqpBm33hKKbds=,tag:vrD1ty3jSUe5bndGBVnBog==,type:str]
    DEFAULT_AUTHENTIK_PG_PASS: ENC[AES256_GCM,data:2wR0ZaJVUYn6GV3YMY1N5cDWd2EMB1QzqTOTds20XBjQdbu4hyReBYWOEgAWTWsn,iv:qqBSOKVaJpBLFUGEfRFDJZknSyn0DR1kOVyoB7PCEao=,tag:7Ho1rhn0wnQTLIrK0AITmA==,type:str]
    DEFAULT_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:luYPW4sYv1s5w5vpHhaXILaod7R5pJ8kUUn4D2lmY+5ksNh/Zw8R51+Cctn4QEax,iv:0pydGcq6rO4LMsYOwQca3qvb/oZGxddcZIgImD0vPcY=,tag:21q4QYCU56ZyO1KzrS72yw==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:NipkbV2so2FpSV1X7qeWKA==,iv:3ct4bIfliNIvs7dEaj3Rbzec5Hi+ikyoE4vecwrLfQs=,tag:WMCw890aHFFQqkMOLcoT5A==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:rclJbnycOmilsfXGIX5bq48ol9/i/MvF,iv:qGAR7ZzNlF2skyi2t4N3u0F9tF7jD0TGnSm5zzVgJhA=,tag:Q/6vduILPPR46fWk5qv+jw==,type:str]
    SECRET_ALERTMANAGER_TELEGRAM_TOKEN: ENC[AES256_GCM,data:8q5Zgr1NBnvjY2iDOMXuYHcwWzLeD4ZCA9PHbQAkmQk90+LqAWFqF41+RrDjMw==,iv:abpOrVKATyMWxETQNNL7F9T6BoVBw1ldjVxxnNtTn4c=,tag:q96+gmZkFTDQztNBhEHRYA==,type:str]
    SECRET_ALERTMANAGER_TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:Gww5qD5//xII,iv:qmOrKC9cv6lURDhUYEsFVPaPTNCWX0MHy+PALcjcBvA=,tag:Yj0yJhTL6gEjgF6txIc3mw==,type:str]
    DEFAULT_FIREFLY_III_DB_NAME: ENC[AES256_GCM,data:Np/pVVukwg==,iv:+nKt6nzV9uK9ytri2xCsYBngA7pLBRmwrE9KVB3VS30=,tag:nq5ZZF9yfu+mWT3Gz2sc9A==,type:str]
    DEFAULT_FIREFLY_III_DB_USER: ENC[AES256_GCM,data:o3NCwaicWg==,iv:FfH83OfqM2vJhjUACDukWa7ApCnhl4XqVBVQbTH6Tc0=,tag:kuCTtMOf9BUORXyTje1J4w==,type:str]
    DEFAULT_FIREFLY_III_DB_PASS: ENC[AES256_GCM,data:nI8VtfyC1SQew3wIr9SrhT1eD5I1JXPNjTk/1Bv8krI=,iv:uknVTonk6fcJJEZjZ65Y1AU7Eo/sO+2yeNLHokFUNfU=,tag:Jv97zq2TJrpuVxQouSgNJQ==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:Mzbd3tUurTRUpxSGaKAPQA==,iv:avvLuBYuQVJ/JAbeEIHAIazwvdHh9g7QM18Rrc+93AA=,tag:rZNfS0/Qti+I/dw2pPWxxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mjwvxuph2r4kvz8lkew4gvfj6xkgyps7mqj724y9akvdd99ljycsur2jrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRjFVY3BJaTd1U1J0OUxJ
            T096cjQ2SjVsNkNiTW1uQzd2YVc3Y0d5c0VrClpJbHRJSkhSc3VWMFovS1d6SWtP
            VmVlaUlJbStqVG5PMXdRbk0rRjBySEEKLS0tIHhuQmVWdTQ0SUZNUnZ6NlBBcFAz
            bmZUNFltVVlyMmdWYm01NmRJOXd3SVkKEB2dl61hXP43kbJoW4g2o4n+Dvdjk6F8
            4dXLI5vIvArs+eQ/GFt8XtNP28c9pOWpOZ4dU7DvviMhj9n5sin6pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-16T20:03:53Z"
    mac: ENC[AES256_GCM,data:UhCrWhU6Sh1AuwmcoF0pdlVYBEvM2jeBEJhZoc8kFW/UIvCUS51fOOW+MQGG+J+hwfboFdV1jknQH3FpefsGWcBhmZP7uO549EzYL6u90Fu/WvNsc2C5RrDmbw0j0UqzESnBZkgbTCshcs/hub7XxtEB+NSCyJKuheBa5dzGKRI=,iv:9+zDoqqcZOBT/+7w6X3c9zoVj9dBg5wXC4SJSIJ05OY=,tag:wzhBvaj8I2RqKIOeTZptjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
