---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: baikal
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: baikal
      version: 4.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ckulka/baikal
      tag: 0.9.2
    env:
      TZ: Europe/Berlin
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns/is-public: "true"
        hosts:
          - host: "baikal.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /var/www/baikal/config
        existingClaim: baikal-config-v1
      data:
        enabled: true
        type: pvc
        mountPath: /var/www/baikal/Specific
        existingClaim: baikal-data-v1
