---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: baikal
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: ckulka/baikal
      tag: 0.9.2
    env:
      TZ: Europe/Berlin
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external.home.arpa/enabled: "true"
        hosts:
          - host: "baikal.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /var/www/baikal/config
        existingClaim: baikal-config-v1
      data:
        enabled: true
        type: pvc
        mountPath: /var/www/baikal/Specific
        existingClaim: baikal-data-v1
