---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      engineVersion: v2
      data:
        password: "{{ .REDIS_PASSWORD }}"
  dataFrom:
    - extract:
        key: REDIS

