---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: external
spec:
  ports:
    - port: 3120

---
apiVersion: v1
kind: Endpoints
metadata:
  name: vaultwarden
  namespace: external
subsets:
  - addresses:
      - ip: 192.168.4.11
    ports:
      - port: 3120

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  namespace: external
  annotations:
    external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
spec:
  ingressClassName: nginx
  rules:
    - host: &host "bw.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaultwarden
                port:
                  number: 3120
  tls:
    - hosts:
        - *host
