---
- name: Install unattended-upgrades package
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600

- name: "Create unattended-upgrades configuration"
  ansible.builtin.template:
    src: "50unattended-upgrades.j2"
    dest: "/etc/apt/apt.conf.d/90-ansible-unattended-upgrades"
    owner: "root"
    group: "root"
    mode: "0644"
