---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mediamtx-secret
  namespace: default
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      engineVersion: v2
      data:
        mediamtx.yml: |
          authInternalUsers:
          - user: stream
            pass: {{ .MEDIAMTX_STREAM_PASSWORD }}
            ips: []
            # List of permissions.
            permissions:
            - action: read
              path:
            - action: playback
              path:
          - user: any
            pass:
            ips: ['127.0.0.1', '::1']
            permissions:
            - action: api
            - action: metrics
            - action: pprof

          rtsp: yes
          protocols: [tcp]
          rtspAddress: :554
          rtpAddress: :8000

          webrtcAddress: :80
          webrtcLocalUDPAddress: :8189

          paths:
            c100:
              source: {{ .MEDIAMTX_C100_RTSP_URL }}
  dataFrom:
    - extract:
        key: MEDIAMTX
