---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mediamtx
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: bluenviron/mediamtx
              tag: 1.8.2
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          external.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.alpha.kubernetes.io/hostname: "mediamtx.${SECRET_DOMAIN}"
          io.cilium/lb-ipam-ips: "${VIP_MEDIAMTX}"
        ports:
          webrtc:
            port: 80
          rtsp:
            port: 554
          rtspudp:
            port: 8000
            protocol: UDP
          webrtcupd:
            port: 8189
            protocol: UDP
    persistence:
      config:
        name: mediamtx-secret
        type: secret
        advancedMounts:
          main:
            main:
              - path: /mediamtx.yml
                readOnly: true
                subPath: mediamtx.yml
