---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: home-dns-external
  namespace: networking

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: home-dns-external
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: home-dns-external
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: home-dns-external
subjects:
  - kind: ServiceAccount
    name: home-dns-external
    namespace: networking
