---
collections:
  - name: ansible.posix
    version: 1.4.0
  - name: community.general
    version: 5.2.0
  - name: kubernetes.core
    version: 2.3.2
  - name: community.sops
    version: 1.2.2
roles:
  - src: xanmanning.k3s
    version: v3.1.2
