---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-ui
  namespace: external
spec:
  ports:
    - port: 3120

---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-ws
  namespace: external
spec:
  ports:
    - port: 3012

---
apiVersion: v1
kind: Endpoints
metadata:
  name: vaultwarden-ui
  namespace: external
subsets:
  - addresses:
      - ip: 192.168.178.144
    ports:
      - port: 3120

---
apiVersion: v1
kind: Endpoints
metadata:
  name: vaultwarden-ws
  namespace: external
subsets:
  - addresses:
      - ip: 192.168.178.144
    ports:
      - port: 3012

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bw.${SECRET_DOMAIN}`)
      kind: Rule
      services:
        - name: vaultwarden-ui
          port: 3120
    - match: Host(`bw.${SECRET_DOMAIN}`) && Path(`/notifications/hub`)
      kind: Rule
      services:
        - name: vaultwarden-ws
          port: 3012
  tls:
    store:
      name: default
