---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-config-v1
  namespace: default
  labels:
    app.kubernetes.io/name: &name freshrss
    app.kubernetes.io/instance: *name
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
