---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-agent
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: vector
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: vector-charts
        namespace: flux-system
  dependsOn:
    - name: loki
      namespace: monitoring
  values:
    image:
      repository: timberio/vector
      tag: 0.24.0-debian
    role: Agent
    # env:
    #   - name: VECTOR_WATCH_CONFIG
    #     value: "true"
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: false
      sources:
        journal_logs:
          type: journald
          journal_directory: /var/log/journal
        kubernetes_logs:
          type: kubernetes_logs
      sinks:
        loki_journal:
          type: loki
          inputs:
            - journal_logs
          endpoint: http://loki:3100
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            hostname: >-
              {{`{{ host }}`}}
        loki_kubernetes:
          type: loki
          inputs:
            - kubernetes_logs
          endpoint: http://loki:3100
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            app: >-
              {{`{{ kubernetes.pod_labels.app\.kubernetes\.io/name }}`}}
            container: >-
              {{`{{ kubernetes.container_name }}`}}
            filename: >-
              {{`{{ kubernetes.file }}`}}
            instance: >-
              {{`{{ kubernetes.pod_labels.app\.kubernetes\.io/instance }}`}}
            namespace: >-
              {{`{{ kubernetes.pod_namespace }}`}}
            node: >-
              {{`{{ kubernetes.pod_node_name }}`}}
            pod: >-
              {{`{{ kubernetes.pod_name }}`}}
    service:
      enabled: false
    podMonitor:
      enabled: true
    securityContext:
      privileged: true
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
