---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authelia
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: ext-postgres-operator
      namespace: database
    - name: redis
      namespace: database
  values:
    controllers:
      main:
        replicas: 2
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/authelia/authelia
              tag: 4.37.5
            command: ["authelia"]
            args: ["--config", "/config/configuration.yaml"]
            env:
              TZ: "${TIMEZONE}"
              AUTHELIA_SERVER_PORT: &port 80
              AUTHELIA_STORAGE_POSTGRES_HOST:
                valueFrom:
                  secretKeyRef:
                    name: pg-authelia
                    key: HOST
              AUTHELIA_STORAGE_POSTGRES_DATABASE:
                valueFrom:
                  secretKeyRef:
                    name: pg-authelia
                    key: DATABASE_NAME
              AUTHELIA_STORAGE_POSTGRES_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: pg-authelia
                    key: LOGIN
              AUTHELIA_STORAGE_POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: pg-authelia
                    key: PASSWORD
              AUTHELIA_SESSION_REDIS_HOST: redis-master.database.svc.cluster.local
              AUTHELIA_SESSION_REDIS_PORT: "6379"
              AUTHELIA_SESSION_REDIS_DATABASE_INDEX: "${REDIS_DB_AUTHELIA}"
              AUTHELIA_SESSION_REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: authelia-ext
                    key: REDIS_PASSWORD
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probe
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 200Mi
        pod:
          enableServiceLinks: false
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          external.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.alpha.kubernetes.io/target: "dex.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header Cache-Control "no-store";
            add_header Pragma "no-cache";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
        hosts:
          - host: "auth.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - "auth.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        type: secret
        name: authelia-config-secret
        globalMounts:
          - path: /config/configuration.yaml
            subPath: configuration.yaml
            readOnly: true
      users:
        enabled: true
        type: secret
        name: authelia-users-secret
        globalMounts:
          - path: /config/users.yaml
            subPath: users.yaml
            readOnly: true
