---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authelia
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/authelia/authelia
      tag: 4.37.5
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    command: ["authelia"]
    args: ["--config", "/config/configuration.yaml"]
    env:
      TZ: "${TIMEZONE}"
      AUTHELIA_SERVER_PORT: &port 80
      AUTHELIA_STORAGE_POSTGRES_HOST:
        valueFrom:
          secretKeyRef:
            name: pg-authelia
            key: HOST
      AUTHELIA_STORAGE_POSTGRES_DATABASE:
        valueFrom:
          secretKeyRef:
            name: pg-authelia
            key: DATABASE_NAME
      AUTHELIA_STORAGE_POSTGRES_USERNAME:
        valueFrom:
          secretKeyRef:
            name: pg-authelia
            key: LOGIN
      AUTHELIA_STORAGE_POSTGRES_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: pg-authelia
            key: PASSWORD
      AUTHELIA_SESSION_REDIS_HOST: redis-master.database.svc.cluster.local
      AUTHELIA_SESSION_REDIS_PORT: "6379"
      AUTHELIA_SESSION_REDIS_DATABASE_INDEX: "${REDIS_DB_AUTHELIA}"
      AUTHELIA_SESSION_REDIS_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: authelia-ext
            key: REDIS_PASSWORD
    enableServiceLinks: false
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.alpha.kubernetes.io/target: "dex.${SECRET_DOMAIN}"
        hosts:
          - host: "auth.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "auth.${SECRET_DOMAIN}"
    probes:
      liveness: &probe
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /api/health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probe
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        type: secret
        name: authelia-config-secret
        subPath: configuration.yaml
        mountPath: /config/configuration.yaml
        readOnly: true
      users:
        enabled: true
        type: secret
        name: authelia-users-secret
        subPath: users.yaml
        mountPath: /config/users.yaml
        readOnly: true
