---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: authelia
  namespace: default
spec:
  database: authelia
  dropOnDelete: false
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: authelia
  namespace: default
spec:
  role: authelia
  database: authelia
  secretName: pg
  privileges: OWNER
