apiVersion: v1
kind: Secret
metadata:
    name: authelia-config-secret
    namespace: kube-system
    annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
stringData:
    configuration.yaml: ENC[AES256_GCM,data:q5M4sbFm+SPIK8J5VlRTNcVJILcSYnZkDLv5FfYe3uV9Rse0jgBUe+RPWaJxpfX6LnsM50v/fceEuzzvNN+23xVMoulQpP74zz/4iSP1C0ASQW6ZuyBPufWgQu1grjDG+IkjKmMsgipYkdJWAjH3KCBU0OUgNJDr1wxanNbY7WBt1vwuwNOrFuI9lEzgbORYZtG8SK6prruiXOdZxjN0u+E42BzcAc/34QKeXjMQ0xln6I1JXv4praWX0s0arNOVxqrfFcWv45rNV8pGwwZJ/XoVvyhpXCp8qP5gOGAwnUCUmKzMgFHZYD0DCpEG8zxfWZm3d2bnx/mhgxbY2tj/d6789a/uECl5BJYtbOljfAiUTgGofFsVC8IHuEvxxbnd0C6HyiX6APexYNPVELVgJ8AEm2lUma74NSxfxN4KWnPPm1nokOv0BwABoNzuaEAkH0pMB86Mm91C4xxLMx3P41hrMObmqphIiTTz1Iba8V8fqz9Yoqp6dYpVT4Fca7651VL5YCtuTjGDxvxVapMFCJ7fNbbtC2HNEFyD7RCHCBI50ixzNnTlX88jUD9K4CUd2rmIYAJbhq53PrbtwJGHI8u0/7KB99nOOYjSVos9/0jwkbAdzNg7GRH2GisuGhYJXZEut9S9cjB5AKdplNoK1VjYfXjRP3jFaNSIFji1aoO3MCshKE8Oft+hSXH1iS1r16qnRX5T/pEFDYThtRuiGSa6TCsChHPkcRT3KqwxdW0hGxNbkbMxzme9/9wB1/DBSGAOCEllKBEN/WmiopHstKOjkA1yeqc6flIT1y9yNYx1X/5QzF5+txfMqM6VToxoK8xXvby5I+UTrGlNfqJrTXd4siHwGajDZROe61131dKzEDNKxOwuqBCOjhnUvS5NEkVQbc5tNxgLku48nxYuKydN97C65MXoAl2beR1iE2nAcOzNKfVNEbGnMtT0UDUN2YDDkwoDcGx+/cbSVVFFmq1ifhaMpUQgvjOf/o8zokJWCZYLndJMNw/OaEw69ynfZA43hAzo944n40Av20+GAr+KHEsUfL89iVRIA+B1afJIzkkBSThPNkAeKJuCy3uj8k3l3IYx/aK/wH8W/WzivV2FiJ+XspTWvhXrBRE/kak+HyE0lNNA9S17N9gAX1NFBS3gSx7ZTjvCeSW6PWuifqA9dg==,iv:4CRcsJbVUCY6WTTFYirKRqxQeGH+qQxP7lptmCyPTnI=,tag:9w9VinSgQvLTPj2kNu1Sgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14pz5aw6h2m05jezv8yasyvalm0sqzpgwxkd8pusve2xwdwm22auqd3qu54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMUlnNFQ3WXpJNE5VckNI
            MVliRDRCZ2ZCTlFoOHJadW9QelJ3TzFhMEhzCkNaYXRqZEF5ZXhXT3lxNi8vNzdM
            Wkx4bkgrUEhyREtteFRpRVEzd2hIcTAKLS0tIFFKamtkUnVSRUtGRHpOT1lQN1Iy
            a2ZQcGx6Sk8wazVvbkowRXhXTlRFS28Ke3t+6RuH8XrhCdNqgtNMk84W6kVGxRSe
            l8IvtMjOkQFbH6FyrA1fWsKFXwoOdZzwg+1diXpUQfesBgEviKglxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-29T13:20:52Z"
    mac: ENC[AES256_GCM,data:EG4jboqOy068ZYyF94HSIH/ufRMbSrc4HpFJIsH/JYQ4n9oXLgzvuQ1pP27H/LuFYDQaKG0Lhr6nROfg6NpDHVVhLUfdmXc5wHMac8NmTie5Bq4FPja5SHK1FZOQ5ycGG8IIX3aTJqpUGb32oj82Lf2qAg55bCt7q2manC8ApgE=,iv:bSqY42vAdG+SDdDYT3GpAnw67Pjxyr9Q46YM+fA8bwA=,tag:L9NSy7+5vqOn7EqNG2srBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-users-secret
    namespace: kube-system
    annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
stringData:
    users.yaml: ENC[AES256_GCM,data:JSHJxIjF+SVwkFKC5PKnQmsR9VEiDY2E1Ou1mRxIbCIK6CAGZ/cjoYxFg253ewu1eRn0kZISHkkMpnj2A6+eAtR7AwwL+wi6XYE7+wXSAY2lwQrZkGyTrxKZLCzU+7vSDCmAh8hYPVKVsqn0+DNJ30/JSZCBdzATuYeBu92ZEXRqXhBHk+wDvVN6u0EYCKwEBYiDPsb3/4M2pwG8Nm4MV3byOg6A0hIyZ4k24NVzRlt4rm4+KAbl9lUGAn2PSfozmUM4+qzN1D0rCiuWIIhzV/s58b7ExpWm8XWoS2ontUZSx0Tof18=,iv:0pM08KmUO6jwhpjYs8eGm1E1lRjYp3Rfq2owQ/GnUvA=,tag:VksmCnUgGjZzYmwXgW+D1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14pz5aw6h2m05jezv8yasyvalm0sqzpgwxkd8pusve2xwdwm22auqd3qu54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMUlnNFQ3WXpJNE5VckNI
            MVliRDRCZ2ZCTlFoOHJadW9QelJ3TzFhMEhzCkNaYXRqZEF5ZXhXT3lxNi8vNzdM
            Wkx4bkgrUEhyREtteFRpRVEzd2hIcTAKLS0tIFFKamtkUnVSRUtGRHpOT1lQN1Iy
            a2ZQcGx6Sk8wazVvbkowRXhXTlRFS28Ke3t+6RuH8XrhCdNqgtNMk84W6kVGxRSe
            l8IvtMjOkQFbH6FyrA1fWsKFXwoOdZzwg+1diXpUQfesBgEviKglxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-29T13:20:52Z"
    mac: ENC[AES256_GCM,data:EG4jboqOy068ZYyF94HSIH/ufRMbSrc4HpFJIsH/JYQ4n9oXLgzvuQ1pP27H/LuFYDQaKG0Lhr6nROfg6NpDHVVhLUfdmXc5wHMac8NmTie5Bq4FPja5SHK1FZOQ5ycGG8IIX3aTJqpUGb32oj82Lf2qAg55bCt7q2manC8ApgE=,iv:bSqY42vAdG+SDdDYT3GpAnw67Pjxyr9Q46YM+fA8bwA=,tag:L9NSy7+5vqOn7EqNG2srBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
