---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tasmoadmin
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    image:
      repository: docker.io/raymondmm/tasmoadmin
      tag: v1.7.0
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            port: 80
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "${VIP_TASMOADMIN}"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "tasmoadmin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: tasmoadmin-data
    resources:
      requests:
        memory: 100Mi
        cpu: 40m
      limits:
        memory: 500Mi
