# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:IrYT0PKnCTgLXltOgzgjdu/9Oq5WPdEfJu80gwvE+L4+7bX9RWCcV27z04Es9qH9dtM44jLEkUnBcR77xjnbNhCysz22/RHsU+HoC84Wgeqn/vIw9RxNj52USFp2RthanQ3GGIvs61d80+i6tbm3D4DRjPciS3n2,iv:nCAp44KNsnaAt8hq59Nc12docz9X+AB/7Bd3cXmyUZg=,tag:CeW32MuVjUEiJbn2rzlpsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mjwvxuph2r4kvz8lkew4gvfj6xkgyps7mqj724y9akvdd99ljycsur2jrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVkdzUnF4VVJQWmhkRHVx
            UmdzaStWMHZFQWFjMkg4QnloZ1NjTlZ0Y1VRCk9icFJrK010VjZveS9Yait3eWJD
            U2hlT2o3NjhYNjNZS2cvSFdzSDJtclUKLS0tIE9JWWNZOXVMc0NiZk0welJJd0Ir
            YTdya1YvRnVvQmFMaGRReHJSYkZ2aDQKOzMpqKm3PwcKFVFHadYRWDqbZOtxRLcF
            nvCMdApPBeNmHSeyJwIzKLwT76aT6rBobNMocc467OihuU1GylDtjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-12T08:37:48Z"
    mac: ENC[AES256_GCM,data:vtiGJXhU3GVvKvfZslEDHNbuJ6+WZ2FNJWFzjEcEFvpTwsKpzsO22eEx7XwWOV7F2udt6e3bDO6YOID3ODRwuaUhmz1AiyoiSn7B3bnRJ0bRl9IzARPRvOmG/jBnzWpGLLtz7ytQDsbfqzqjlcdunWC5iVoFxt6/ns8Sql4Jg7c=,iv:ApvwjQPLI5Ppn/8arxl6gFyNm1+tA5pimnrL3OuN+34=,tag:DSGcgtdY/67Ej4uR7owKCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
