---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template-postgres
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: custom-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2023.7.3
    env:
      TZ: "${TIMEZONE}"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "ha.${SECRET_DOMAIN}"
          io.cilium/lb-ipam-ips: "${VIP_HOME_ASSISTANT}"
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ha.${SECRET_DOMAIN}"
        hosts:
          - host: "ha.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    # TODO: maybe enable probes
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    nodeSelector:
      kubernetes.io/hostname: helios
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: home-assistant-config
      dbus:
        enabled: true
        type: hostPath
        hostPath: /run/dbus
    additionalContainers:
      appdaemon:
        name: appdaemon
        image: docker.io/acockburn/appdaemon:4.4.2
        env:
          - name: TZ
            value: "${TIMEZONE}"
        volumeMounts:
          - name: config
            subPath: appdaemon
            mountPath: /conf
    postgresql:
      enabled: true
      nameOverride: postgresql
      auth:
        username: home-assistant
        database: home-assistant
        existingSecret: ha-postgresql-secret
      primary:
        enabled: true
        persistence:
          enabled: true
          existingClaim: home-assistant-postgres
        nodeSelector:
          kubernetes.io/hostname: helios
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.13.0
        env:
          TZ: "${TIMEZONE}"
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
          hosts:
            - host: "ha-config.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      requests:
        memory: 750Mi
        cpu: 200m
      limits:
        memory: 2500Mi
