---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2023.11.2
            env:
              TZ: "${TIMEZONE}"
            envFrom:
              - secretRef:
                  name: pg-home-assistant-user
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                memory: 750Mi
                cpu: 200m
              limits:
                memory: 2500Mi
          appdaemon:
            image:
              repository: docker.io/acockburn/appdaemon
              tag: 4.4.2
            env:
              TZ: "${TIMEZONE}"
        pod:
          nodeSelector:
            feature.node.kubernetes.io/custom-sonoff-zigbee: "true"
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "${VIP_HOME_ASSISTANT}"
        ports:
          http:
            port: 8123
          homekit:
            port: 21063
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &host "ha.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
        globalMounts:
        advancedMounts:
          main:
            main:
              - path: /config
            appdaemon:
              - path: /conf
                subPath: appdaemon
      dbus:
        enabled: true
        type: hostPath
        advancedMounts:
          main:
            main:
              - path: /run/dbus
