---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-auth
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      engineVersion: v2
      data:
        api-token: "{{ .API_TOKEN }}"
        TS_AUTHKEY: "{{ .TAILSCALE_OAUTH_K8S_OPERATOR_CLIENT_SECRET }}?preauthorized=true"
  dataFrom:
    - extract:
        key: TAILSCALE
