---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # dependsOn:
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.56.1
            env:
              TS_KUBE_SECRET: tailscale-state-1
              TS_USERSPACE: &TS_USERSPACE "true"
              # TS_ROUTES: "${CLUSTER_CIDR},${SERVICE_CIDR}"
              TS_ROUTES: &TS_ROUTES "10.43.100.100/32" # external proxy ingress service
              TS_EXTRA_ARGS: &TS_EXTRA_ARGS --advertise-tags=tag:k8s-operator
              # TS_HOSTNAME: k8s-gateway-tailscale
              TS_AUTHKEY:
                valueFrom:
                  secretKeyRef:
                    name: tailscale-auth-1
                    key: TS_AUTHKEY
      # second pod for failover
      # https://tailscale.com/kb/1115/high-availability#failover
      secondary:
        enabled: true
        containers:
          main:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.56.1
            env:
              TS_KUBE_SECRET: tailscale-state-2
              TS_USERSPACE: *TS_USERSPACE
              TS_ROUTES: *TS_ROUTES
              TS_EXTRA_ARGS: *TS_EXTRA_ARGS
              TS_AUTHKEY:
                valueFrom:
                  secretKeyRef:
                    name: tailscale-auth-2
                    key: TS_AUTHKEY
    defaultPodOptions:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values: ["tailscale"]
              topologyKey: kubernetes.io/hostname
    service:
      main:
        enabled: false
    serviceAccount:
      name: tailscale
