---
kubernetes:
  vars:
    ansible_user: kube
  children:
    master:
      hosts:
        # neon:
        #   ansible_host: 192.168.4.11
        volt:
          ansible_host: 192.168.4.13
        arc:
          ansible_host: 192.168.4.14
        xenon:
          ansible_host: 192.168.4.12
    workers:
      hosts:
        helios:
          ansible_host: 192.168.4.10
