---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: node-red
      version: 10.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/node-red
      tag: v2.2.2
    env:
      TZ: "Europe/Berlin"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_CREDENTIAL_SECRET:
        valueFrom:
          secretKeyRef:
            name: node-red
            key: credential-secret
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-local-only@kubernetescrd"
        hosts:
          - host: "node-red.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 100
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: node-red-data-v1
      settings:
        enabled: true
        type: custom
        volumeSpec:
          configMap:
            name: node-red-settings-js
        subPath:
          - path: settings.js
            mountPath: /data/settings.js
            readOnly: true
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 700Mi
