---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: nodered/node-red
      tag: 3.0.2
    env:
      TZ: "Europe/Berlin"
      FLOWS: flows.json
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_CREDENTIAL_SECRET:
        valueFrom:
          secretKeyRef:
            name: node-red
            key: credential-secret
    service:
      main:
        ports:
          http:
            port: 1880
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "node-red.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 100
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: node-red-data-v1
      settings:
        enabled: true
        type: custom
        volumeSpec:
          configMap:
            name: node-red-settings-js
        subPath:
          - path: settings.js
            mountPath: /data/settings.js
            readOnly: true
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 700Mi
