---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-external-provisioner
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
  values:
    image:
      repository: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.2
    nfs:
      server: "${NAS_ADDR}"
      path: /volumeUSB1/usbshare/nfs-provisioner
    storageClass:
      create: true
      provisionerName: nfs-subdir-external-provisioner
      defaultClass: false
      name: nfs-client
