---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: calibre
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/linuxserver/calibre
      tag: version-v6.0.0
    env:
      TZ: Europe/Berlin
    service:
      webserver:
        enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        hosts:
          - host: "calibre.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: calibre-config-v1
      nfs-nas-media:
        enabled: true
        type: nfs
        server: "${NAS_ADDR}"
        path: /volume1/ebooks/calibre
        mountPath: /data
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 1Gi
