---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actual
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: jlongster/actual-server
      tag: 23.4.0
      pullPolicy: IfNotPresent
    nameOverride: actual
    env:
      TZ: Europe/Berlin
    service:
      main:
        ports:
          http:
            port: 5006
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "actual.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      server-files:
        enabled: true
        type: pvc
        mountPath: /app/server-files
        existingClaim: actual-server-files-v1
      user-files:
        enabled: true
        type: pvc
        mountPath: /app/user-files
        existingClaim: actual-user-files-v1
    resources:
      requests:
        memory: 300Mi
        cpu: 200m
      limits:
        memory: 800Mi
