---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-server-files-v1
  namespace: default
  labels:
    app.kubernetes.io/name: &name actual
    app.kubernetes.io/instance: *name
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-user-files-v1
  namespace: default
  labels:
    app.kubernetes.io/name: &name actual
    app.kubernetes.io/instance: *name
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
