---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniflux-postgresql-v1
  namespace: default
  labels:
    app.kubernetes.io/name: &name miniflux-postgresql
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
