---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s

# (bool) Specify if a host (or host group) are part of the control plane
k3s_control_node: true

# (dict) k3s settings for all control-plane nodes
k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
    - "{{ kubevip_address }}"
  docker: false
  flannel-backend: "none"
  disable:
    - flannel
    - traefik
    - servicelb
    - metrics-server
  disable-network-policy: true
  disable-cloud-controller: true
  write-kubeconfig-mode: "644"
  cluster-cidr: "10.42.0.0/16"
  service-cidr: "10.43.0.0/16"
  etcd-expose-metrics: true
  kube-controller-manager-arg:
    # Required to monitor kube-controller-manager with kube-prometheus-stack
    - "bind-address=0.0.0.0"
  kube-proxy-arg:
    # Required to monitor kube-proxy with kube-prometheus-stack
    - "metrics-bind-address=0.0.0.0"
  kube-scheduler-arg:
    # Required to monitor kube-scheduler with kube-prometheus-stack
    - "bind-address=0.0.0.0"
  kube-apiserver-arg:
    # Required for HAProxy health-checks
    - "anonymous-auth=true"