---
# MegaLinter GitHub Action configuration file
# More info at https://megalinter.github.io
name: MegaLinter

on:
  # Trigger mega-linter at every push. Action will also be visible from Pull Requests to master
  # push: # Comment this line to trigger action only on pull-requests (not recommended if you don't pay for GH Actions)
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # MegaLinter
      - name: MegaLinter
        id: ml
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.github.io/flavors/
        uses: megalinter/megalinter/flavors/documentation@v6
        env:
          # All available variables are described in documentation
          # https://megalinter.github.io/configuration/
          # VALIDATE_ALL_CODEBASE: ${{ github.event_name == &#39;push&#39; &amp;&amp; github.ref == &#39;refs/heads/main&#39; }} # Validates all source when push on main, else just the git diff with main. Set &#39;true&#39; if you always want to lint all sources
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # ADD YOUR CUSTOM ENV VARIABLES HERE TO OVERRIDE VALUES OF .mega-linter.yml AT THE ROOT OF YOUR REPOSITORY
          ENABLE_LINTERS: ACTION_ACTIONLINT,ANSIBLE_ANSIBLE_LINT,BASH_SHELLCHECK,DOCKERFILE_HADOLINT,ENV_DOTENV_LINTER,GIT_GIT_DIFF,JSON_JSONLINT,KUBERNETES_KUBEVAL,MARKDOWN_MARKDOWNLINT,YAML_YAMLLINT
          ANSIBLE_DIRECTORY: ansible
          ANSIBLE_ANSIBLE_LINT_CONFIG_FILE: .ansible-lint
          KUBERNETES_DIRECTORY: cluster
          KUBERNETES_KUBEVAL_ARGUMENTS: --ignore-missing-schemas
          MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yaml
          YAML_YAMLLINT_CONFIG_FILE: .yamllint.yaml

      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: MegaLinter reports
          path: |
            report
            mega-linter.log
